// Code generated by wit-bindgen-go. DO NOT EDIT.

package cv

import (
	"github.com/hybridgroup/wasmcv/components/tinygo/wasm/cv/types"
)

func lower_Size(v types.Size) (f0 uint32, f1 uint32) {
	f0 = (uint32)(v.X)
	f1 = (uint32)(v.Y)
	return
}
