// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package request represents the exported interface "wasm:cv/request".
//
// request resource is a request from host for guest module to process an image.
package request

import (
	"github.com/bytecodealliance/wasm-tools-go/cm"
	"github.com/hybridgroup/wasmcv/components/tinygo/wasm/cv/mat"
)

//go:wasmexport wasm:cv/request#process
//export wasm:cv/request#process
func wasmexport_Process(image0 uint32) (result0 uint32) {
	image := cm.Reinterpret[mat.Mat]((uint32)(image0))
	result := Exports.Process(image)
	result0 = cm.Reinterpret[uint32](result)
	return
}
