// Generated by `wit-bindgen` 0.31.0. DO NOT EDIT!
// Options used:
pub type BorderType = wasm::cv::types::BorderType;
pub type Size = wasm::cv::types::Size;
pub type AdaptiveThresholdType = wasm::cv::types::AdaptiveThresholdType;
pub type ThresholdType = wasm::cv::types::ThresholdType;
pub type Mat = wasm::cv::mat::Mat;
#[allow(unused_unsafe, clippy::all)]
/// AdaptiveThreshold applies a fixed-level threshold to each array element.
/// For further details, please see:
/// https://docs.opencv.org/master/d7/d1b/group__imgproc__misc.html#ga72b913f352e4a1b1b397736707afcde3
pub fn adaptive_threshold(src: Mat,max_value: f32,adaptive_type: AdaptiveThresholdType,threshold_type: ThresholdType,block_size: u32,c: f32,) -> Mat{
  unsafe {

    #[cfg(target_arch = "wasm32")]
    #[link(wasm_import_module = "$root")]
    extern "C" {
      #[link_name = "adaptive-threshold"]
      fn wit_import(_: i32, _: f32, _: i32, _: i32, _: i32, _: f32, ) -> i32;
    }

    #[cfg(not(target_arch = "wasm32"))]
    fn wit_import(_: i32, _: f32, _: i32, _: i32, _: i32, _: f32, ) -> i32{ unreachable!() }
    let ret = wit_import((&src).take_handle() as i32, _rt::as_f32(&max_value), adaptive_type.clone() as i32, threshold_type.clone() as i32, _rt::as_i32(&block_size), _rt::as_f32(&c));
    wasm::cv::mat::Mat::from_handle(ret as u32)
  }
}
#[allow(unused_unsafe, clippy::all)]
/// Blur blurs an image Mat using a normalized box filter.
/// For further details, please see:
/// https://docs.opencv.org/master/d4/d86/group__imgproc__filter.html#ga8c45db9afe636703801b0b2e440fce37
pub fn blur(src: Mat,k_size: Size,) -> Mat{
  unsafe {
    let wasm::cv::types::Size{ x:x0, y:y0, } = k_size;

    #[cfg(target_arch = "wasm32")]
    #[link(wasm_import_module = "$root")]
    extern "C" {
      #[link_name = "blur"]
      fn wit_import(_: i32, _: i32, _: i32, ) -> i32;
    }

    #[cfg(not(target_arch = "wasm32"))]
    fn wit_import(_: i32, _: i32, _: i32, ) -> i32{ unreachable!() }
    let ret = wit_import((&src).take_handle() as i32, _rt::as_i32(x0), _rt::as_i32(y0));
    wasm::cv::mat::Mat::from_handle(ret as u32)
  }
}
#[allow(unused_unsafe, clippy::all)]
/// BoxFilter blurs an image using the box filter.
/// For further details, please see:
/// https://docs.opencv.org/master/d4/d86/group__imgproc__filter.html#gad533230ebf2d42509547d514f7d3fbc3
pub fn box_filter(src: Mat,depth: u32,k_size: Size,) -> Mat{
  unsafe {
    let wasm::cv::types::Size{ x:x0, y:y0, } = k_size;

    #[cfg(target_arch = "wasm32")]
    #[link(wasm_import_module = "$root")]
    extern "C" {
      #[link_name = "box-filter"]
      fn wit_import(_: i32, _: i32, _: i32, _: i32, ) -> i32;
    }

    #[cfg(not(target_arch = "wasm32"))]
    fn wit_import(_: i32, _: i32, _: i32, _: i32, ) -> i32{ unreachable!() }
    let ret = wit_import((&src).take_handle() as i32, _rt::as_i32(&depth), _rt::as_i32(x0), _rt::as_i32(y0));
    wasm::cv::mat::Mat::from_handle(ret as u32)
  }
}
#[allow(unused_unsafe, clippy::all)]
/// GaussianBlur blurs an image using a Gaussian filter.
/// For further details, please see:
/// https://docs.opencv.org/4.x/d4/d86/group__imgproc__filter.html#gae8bdcd9154ed5ca3cbc1766d960f45c1
pub fn gaussian_blur(src: Mat,size: Size,sigma_x: f32,sigma_y: f32,border: BorderType,) -> Mat{
  unsafe {
    let wasm::cv::types::Size{ x:x0, y:y0, } = size;

    #[cfg(target_arch = "wasm32")]
    #[link(wasm_import_module = "$root")]
    extern "C" {
      #[link_name = "gaussian-blur"]
      fn wit_import(_: i32, _: i32, _: i32, _: f32, _: f32, _: i32, ) -> i32;
    }

    #[cfg(not(target_arch = "wasm32"))]
    fn wit_import(_: i32, _: i32, _: i32, _: f32, _: f32, _: i32, ) -> i32{ unreachable!() }
    let ret = wit_import((&src).take_handle() as i32, _rt::as_i32(x0), _rt::as_i32(y0), _rt::as_f32(&sigma_x), _rt::as_f32(&sigma_y), border.clone() as i32);
    wasm::cv::mat::Mat::from_handle(ret as u32)
  }
}
#[allow(unused_unsafe, clippy::all)]
/// Threshold applies a fixed-level threshold to each array element.
/// For further details, please see:
/// https://docs.opencv.org/3.3.0/d7/d1b/group__imgproc__misc.html#gae8a4a146d1ca78c626a53577199e9c57
pub fn threshold(src: Mat,thresh: f32,max_value: f32,threshold_type: ThresholdType,) -> Mat{
  unsafe {

    #[cfg(target_arch = "wasm32")]
    #[link(wasm_import_module = "$root")]
    extern "C" {
      #[link_name = "threshold"]
      fn wit_import(_: i32, _: f32, _: f32, _: i32, ) -> i32;
    }

    #[cfg(not(target_arch = "wasm32"))]
    fn wit_import(_: i32, _: f32, _: f32, _: i32, ) -> i32{ unreachable!() }
    let ret = wit_import((&src).take_handle() as i32, _rt::as_f32(&thresh), _rt::as_f32(&max_value), threshold_type.clone() as i32);
    wasm::cv::mat::Mat::from_handle(ret as u32)
  }
}
#[allow(dead_code)]
pub mod wasm {
  #[allow(dead_code)]
  pub mod cv {
    #[allow(dead_code, clippy::all)]
    pub mod types {
      #[used]
      #[doc(hidden)]
      static __FORCE_SECTION_REF: fn() =
      super::super::super::__link_custom_section_describing_imports;
      
      #[repr(C)]
      #[derive(Clone, Copy)]
      pub struct Size {
        pub x: i32,
        pub y: i32,
      }
      impl ::core::fmt::Debug for Size {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          f.debug_struct("Size").field("x", &self.x).field("y", &self.y).finish()
        }
      }
      #[repr(u8)]
      #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
      pub enum BorderType {
        BorderConstant,
        BorderReplicate,
        BorderReflect,
        BorderWrap,
        BorderReflect101,
        BorderTransparent,
        BorderDefault,
        BorderIsolated,
      }
      impl ::core::fmt::Debug for BorderType {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          match self {
            BorderType::BorderConstant => {
              f.debug_tuple("BorderType::BorderConstant").finish()
            }
            BorderType::BorderReplicate => {
              f.debug_tuple("BorderType::BorderReplicate").finish()
            }
            BorderType::BorderReflect => {
              f.debug_tuple("BorderType::BorderReflect").finish()
            }
            BorderType::BorderWrap => {
              f.debug_tuple("BorderType::BorderWrap").finish()
            }
            BorderType::BorderReflect101 => {
              f.debug_tuple("BorderType::BorderReflect101").finish()
            }
            BorderType::BorderTransparent => {
              f.debug_tuple("BorderType::BorderTransparent").finish()
            }
            BorderType::BorderDefault => {
              f.debug_tuple("BorderType::BorderDefault").finish()
            }
            BorderType::BorderIsolated => {
              f.debug_tuple("BorderType::BorderIsolated").finish()
            }
          }
        }
      }

      impl BorderType{
        #[doc(hidden)]
        pub unsafe fn _lift(val: u8) -> BorderType{
          if !cfg!(debug_assertions) {
            return ::core::mem::transmute(val);
          }

          match val {
            0 => BorderType::BorderConstant,
            1 => BorderType::BorderReplicate,
            2 => BorderType::BorderReflect,
            3 => BorderType::BorderWrap,
            4 => BorderType::BorderReflect101,
            5 => BorderType::BorderTransparent,
            6 => BorderType::BorderDefault,
            7 => BorderType::BorderIsolated,

            _ => panic!("invalid enum discriminant"),
          }
        }
      }

      #[repr(u8)]
      #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
      pub enum AdaptiveThresholdType {
        AdaptiveThresholdMean,
        AdaptiveThresholdGaussian,
      }
      impl ::core::fmt::Debug for AdaptiveThresholdType {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          match self {
            AdaptiveThresholdType::AdaptiveThresholdMean => {
              f.debug_tuple("AdaptiveThresholdType::AdaptiveThresholdMean").finish()
            }
            AdaptiveThresholdType::AdaptiveThresholdGaussian => {
              f.debug_tuple("AdaptiveThresholdType::AdaptiveThresholdGaussian").finish()
            }
          }
        }
      }

      impl AdaptiveThresholdType{
        #[doc(hidden)]
        pub unsafe fn _lift(val: u8) -> AdaptiveThresholdType{
          if !cfg!(debug_assertions) {
            return ::core::mem::transmute(val);
          }

          match val {
            0 => AdaptiveThresholdType::AdaptiveThresholdMean,
            1 => AdaptiveThresholdType::AdaptiveThresholdGaussian,

            _ => panic!("invalid enum discriminant"),
          }
        }
      }

      #[repr(u8)]
      #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
      pub enum ThresholdType {
        ThresholdBinary,
        ThresholdBinaryInv,
        ThresholdTrunc,
        ThresholdToZero,
        ThresholdToZeroInv,
        ThresholdMask,
        ThresholdOtsu,
        TthresholdTriangle,
      }
      impl ::core::fmt::Debug for ThresholdType {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          match self {
            ThresholdType::ThresholdBinary => {
              f.debug_tuple("ThresholdType::ThresholdBinary").finish()
            }
            ThresholdType::ThresholdBinaryInv => {
              f.debug_tuple("ThresholdType::ThresholdBinaryInv").finish()
            }
            ThresholdType::ThresholdTrunc => {
              f.debug_tuple("ThresholdType::ThresholdTrunc").finish()
            }
            ThresholdType::ThresholdToZero => {
              f.debug_tuple("ThresholdType::ThresholdToZero").finish()
            }
            ThresholdType::ThresholdToZeroInv => {
              f.debug_tuple("ThresholdType::ThresholdToZeroInv").finish()
            }
            ThresholdType::ThresholdMask => {
              f.debug_tuple("ThresholdType::ThresholdMask").finish()
            }
            ThresholdType::ThresholdOtsu => {
              f.debug_tuple("ThresholdType::ThresholdOtsu").finish()
            }
            ThresholdType::TthresholdTriangle => {
              f.debug_tuple("ThresholdType::TthresholdTriangle").finish()
            }
          }
        }
      }

      impl ThresholdType{
        #[doc(hidden)]
        pub unsafe fn _lift(val: u8) -> ThresholdType{
          if !cfg!(debug_assertions) {
            return ::core::mem::transmute(val);
          }

          match val {
            0 => ThresholdType::ThresholdBinary,
            1 => ThresholdType::ThresholdBinaryInv,
            2 => ThresholdType::ThresholdTrunc,
            3 => ThresholdType::ThresholdToZero,
            4 => ThresholdType::ThresholdToZeroInv,
            5 => ThresholdType::ThresholdMask,
            6 => ThresholdType::ThresholdOtsu,
            7 => ThresholdType::TthresholdTriangle,

            _ => panic!("invalid enum discriminant"),
          }
        }
      }


    }

    #[allow(dead_code, clippy::all)]
    pub mod mat {
      #[used]
      #[doc(hidden)]
      static __FORCE_SECTION_REF: fn() =
      super::super::super::__link_custom_section_describing_imports;
      
      use super::super::super::_rt;
      #[repr(u8)]
      #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
      pub enum Mattype {
        Cv8u,
        Cv8s,
        Cv16u,
        Cv16s,
        Cv32s,
        Cv32f,
        Cv64f,
      }
      impl ::core::fmt::Debug for Mattype {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          match self {
            Mattype::Cv8u => {
              f.debug_tuple("Mattype::Cv8u").finish()
            }
            Mattype::Cv8s => {
              f.debug_tuple("Mattype::Cv8s").finish()
            }
            Mattype::Cv16u => {
              f.debug_tuple("Mattype::Cv16u").finish()
            }
            Mattype::Cv16s => {
              f.debug_tuple("Mattype::Cv16s").finish()
            }
            Mattype::Cv32s => {
              f.debug_tuple("Mattype::Cv32s").finish()
            }
            Mattype::Cv32f => {
              f.debug_tuple("Mattype::Cv32f").finish()
            }
            Mattype::Cv64f => {
              f.debug_tuple("Mattype::Cv64f").finish()
            }
          }
        }
      }

      impl Mattype{
        #[doc(hidden)]
        pub unsafe fn _lift(val: u8) -> Mattype{
          if !cfg!(debug_assertions) {
            return ::core::mem::transmute(val);
          }

          match val {
            0 => Mattype::Cv8u,
            1 => Mattype::Cv8s,
            2 => Mattype::Cv16u,
            3 => Mattype::Cv16s,
            4 => Mattype::Cv32s,
            5 => Mattype::Cv32f,
            6 => Mattype::Cv64f,

            _ => panic!("invalid enum discriminant"),
          }
        }
      }


      #[derive(Debug)]
      #[repr(transparent)]
      pub struct Mat{
        handle: _rt::Resource<Mat>,
      }

      impl Mat{
        #[doc(hidden)]
        pub unsafe fn from_handle(handle: u32) -> Self {
          Self {
            handle: _rt::Resource::from_handle(handle),
          }
        }

        #[doc(hidden)]
        pub fn take_handle(&self) -> u32 {
          _rt::Resource::take_handle(&self.handle)
        }

        #[doc(hidden)]
        pub fn handle(&self) -> u32 {
          _rt::Resource::handle(&self.handle)
        }
      }


      unsafe impl _rt::WasmResource for Mat{
        #[inline]
        unsafe fn drop(_handle: u32) {
          #[cfg(not(target_arch = "wasm32"))]
          unreachable!();

          #[cfg(target_arch = "wasm32")]
          {
            #[link(wasm_import_module = "wasm:cv/mat")]
            extern "C" {
              #[link_name = "[resource-drop]mat"]
              fn drop(_: u32);
            }

            drop(_handle);
          }
        }
      }

      impl Mat {
        #[allow(unused_unsafe, clippy::all)]
        pub fn new(cols: u32,rows: u32,type_: Mattype,) -> Self{
          unsafe {

            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "wasm:cv/mat")]
            extern "C" {
              #[link_name = "[constructor]mat"]
              fn wit_import(_: i32, _: i32, _: i32, ) -> i32;
            }

            #[cfg(not(target_arch = "wasm32"))]
            fn wit_import(_: i32, _: i32, _: i32, ) -> i32{ unreachable!() }
            let ret = wit_import(_rt::as_i32(&cols), _rt::as_i32(&rows), type_.clone() as i32);
            Mat::from_handle(ret as u32)
          }
        }
      }
      impl Mat {
        #[allow(unused_unsafe, clippy::all)]
        /// close the Mat
        pub fn close(&self,){
          unsafe {

            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "wasm:cv/mat")]
            extern "C" {
              #[link_name = "[method]mat.close"]
              fn wit_import(_: i32, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            fn wit_import(_: i32, ){ unreachable!() }
            wit_import((self).handle() as i32);
          }
        }
      }
      impl Mat {
        #[allow(unused_unsafe, clippy::all)]
        /// Cols returns the number of columns for this Mat.
        pub fn cols(&self,) -> u32{
          unsafe {

            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "wasm:cv/mat")]
            extern "C" {
              #[link_name = "[method]mat.cols"]
              fn wit_import(_: i32, ) -> i32;
            }

            #[cfg(not(target_arch = "wasm32"))]
            fn wit_import(_: i32, ) -> i32{ unreachable!() }
            let ret = wit_import((self).handle() as i32);
            ret as u32
          }
        }
      }
      impl Mat {
        #[allow(unused_unsafe, clippy::all)]
        /// Rows returns the number of rows for this Mat.
        pub fn rows(&self,) -> u32{
          unsafe {

            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "wasm:cv/mat")]
            extern "C" {
              #[link_name = "[method]mat.rows"]
              fn wit_import(_: i32, ) -> i32;
            }

            #[cfg(not(target_arch = "wasm32"))]
            fn wit_import(_: i32, ) -> i32{ unreachable!() }
            let ret = wit_import((self).handle() as i32);
            ret as u32
          }
        }
      }
      impl Mat {
        #[allow(unused_unsafe, clippy::all)]
        /// type returns the type of the Mat.
        pub fn type_(&self,) -> Mattype{
          unsafe {

            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "wasm:cv/mat")]
            extern "C" {
              #[link_name = "[method]mat.type"]
              fn wit_import(_: i32, ) -> i32;
            }

            #[cfg(not(target_arch = "wasm32"))]
            fn wit_import(_: i32, ) -> i32{ unreachable!() }
            let ret = wit_import((self).handle() as i32);
            Mattype::_lift(ret as u8)
          }
        }
      }
      impl Mat {
        #[allow(unused_unsafe, clippy::all)]
        /// Size returns an array with one element for each dimension containing the size of that dimension for the Mat.
        pub fn size(&self,) -> _rt::Vec::<u32>{
          unsafe {
            #[repr(align(4))]
            struct RetArea([::core::mem::MaybeUninit::<u8>; 8]);
            let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 8]);
            let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "wasm:cv/mat")]
            extern "C" {
              #[link_name = "[method]mat.size"]
              fn wit_import(_: i32, _: *mut u8, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            fn wit_import(_: i32, _: *mut u8, ){ unreachable!() }
            wit_import((self).handle() as i32, ptr0);
            let l1 = *ptr0.add(0).cast::<*mut u8>();
            let l2 = *ptr0.add(4).cast::<usize>();
            let len3 = l2;
            _rt::Vec::from_raw_parts(l1.cast(), len3, len3)
          }
        }
      }
      impl Mat {
        #[allow(unused_unsafe, clippy::all)]
        /// empty returns true if the Mat is empty.
        pub fn empty(&self,) -> bool{
          unsafe {

            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "wasm:cv/mat")]
            extern "C" {
              #[link_name = "[method]mat.empty"]
              fn wit_import(_: i32, ) -> i32;
            }

            #[cfg(not(target_arch = "wasm32"))]
            fn wit_import(_: i32, ) -> i32{ unreachable!() }
            let ret = wit_import((self).handle() as i32);
            _rt::bool_lift(ret as u8)
          }
        }
      }
      impl Mat {
        #[allow(unused_unsafe, clippy::all)]
        /// Reshape changes the shape and/or the number of channels of a 2D matrix without copying the data.
        ///
        /// For further details, please see:
        /// https://docs.opencv.org/4.x/d3/d63/classcv_1_1Mat.html#a4eb96e3251417fa88b78e2abd6cfd7d8
        pub fn reshape(&self,channels: u32,rows: u32,) -> Mat{
          unsafe {

            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "wasm:cv/mat")]
            extern "C" {
              #[link_name = "[method]mat.reshape"]
              fn wit_import(_: i32, _: i32, _: i32, ) -> i32;
            }

            #[cfg(not(target_arch = "wasm32"))]
            fn wit_import(_: i32, _: i32, _: i32, ) -> i32{ unreachable!() }
            let ret = wit_import((self).handle() as i32, _rt::as_i32(&channels), _rt::as_i32(&rows));
            Mat::from_handle(ret as u32)
          }
        }
      }

    }

    #[allow(dead_code, clippy::all)]
    pub mod net {
      #[used]
      #[doc(hidden)]
      static __FORCE_SECTION_REF: fn() =
      super::super::super::__link_custom_section_describing_imports;
      
      use super::super::super::_rt;
      pub type Mat = super::super::super::wasm::cv::mat::Mat;
      #[repr(u8)]
      #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
      pub enum NetBackendType {
        NetBackendDefault,
        NetBackendHalide,
        NetBackendOpenvino,
        NetBackendOpencv,
        NetBackendVkcom,
        NetBackendCuda,
      }
      impl ::core::fmt::Debug for NetBackendType {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          match self {
            NetBackendType::NetBackendDefault => {
              f.debug_tuple("NetBackendType::NetBackendDefault").finish()
            }
            NetBackendType::NetBackendHalide => {
              f.debug_tuple("NetBackendType::NetBackendHalide").finish()
            }
            NetBackendType::NetBackendOpenvino => {
              f.debug_tuple("NetBackendType::NetBackendOpenvino").finish()
            }
            NetBackendType::NetBackendOpencv => {
              f.debug_tuple("NetBackendType::NetBackendOpencv").finish()
            }
            NetBackendType::NetBackendVkcom => {
              f.debug_tuple("NetBackendType::NetBackendVkcom").finish()
            }
            NetBackendType::NetBackendCuda => {
              f.debug_tuple("NetBackendType::NetBackendCuda").finish()
            }
          }
        }
      }

      impl NetBackendType{
        #[doc(hidden)]
        pub unsafe fn _lift(val: u8) -> NetBackendType{
          if !cfg!(debug_assertions) {
            return ::core::mem::transmute(val);
          }

          match val {
            0 => NetBackendType::NetBackendDefault,
            1 => NetBackendType::NetBackendHalide,
            2 => NetBackendType::NetBackendOpenvino,
            3 => NetBackendType::NetBackendOpencv,
            4 => NetBackendType::NetBackendVkcom,
            5 => NetBackendType::NetBackendCuda,

            _ => panic!("invalid enum discriminant"),
          }
        }
      }

      #[repr(u8)]
      #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
      pub enum NetTargetType {
        NetTargetCpu,
        NetTargetFp32,
        NetTargetFp16,
        NetTargetVpu,
        NetTargetVulkan,
        NetTargetFpga,
        NetTargetCuda,
        NetTargetCudaFp16,
      }
      impl ::core::fmt::Debug for NetTargetType {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          match self {
            NetTargetType::NetTargetCpu => {
              f.debug_tuple("NetTargetType::NetTargetCpu").finish()
            }
            NetTargetType::NetTargetFp32 => {
              f.debug_tuple("NetTargetType::NetTargetFp32").finish()
            }
            NetTargetType::NetTargetFp16 => {
              f.debug_tuple("NetTargetType::NetTargetFp16").finish()
            }
            NetTargetType::NetTargetVpu => {
              f.debug_tuple("NetTargetType::NetTargetVpu").finish()
            }
            NetTargetType::NetTargetVulkan => {
              f.debug_tuple("NetTargetType::NetTargetVulkan").finish()
            }
            NetTargetType::NetTargetFpga => {
              f.debug_tuple("NetTargetType::NetTargetFpga").finish()
            }
            NetTargetType::NetTargetCuda => {
              f.debug_tuple("NetTargetType::NetTargetCuda").finish()
            }
            NetTargetType::NetTargetCudaFp16 => {
              f.debug_tuple("NetTargetType::NetTargetCudaFp16").finish()
            }
          }
        }
      }

      impl NetTargetType{
        #[doc(hidden)]
        pub unsafe fn _lift(val: u8) -> NetTargetType{
          if !cfg!(debug_assertions) {
            return ::core::mem::transmute(val);
          }

          match val {
            0 => NetTargetType::NetTargetCpu,
            1 => NetTargetType::NetTargetFp32,
            2 => NetTargetType::NetTargetFp16,
            3 => NetTargetType::NetTargetVpu,
            4 => NetTargetType::NetTargetVulkan,
            5 => NetTargetType::NetTargetFpga,
            6 => NetTargetType::NetTargetCuda,
            7 => NetTargetType::NetTargetCudaFp16,

            _ => panic!("invalid enum discriminant"),
          }
        }
      }

      #[repr(u8)]
      #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
      pub enum DataLayoutType {
        DataLayoutUnknown,
        DataLayoutNd,
        DataLayoutNchw,
        DataLayoutNhwc,
        DataLayoutNdhwc,
        DataLayoutPlanar,
      }
      impl ::core::fmt::Debug for DataLayoutType {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          match self {
            DataLayoutType::DataLayoutUnknown => {
              f.debug_tuple("DataLayoutType::DataLayoutUnknown").finish()
            }
            DataLayoutType::DataLayoutNd => {
              f.debug_tuple("DataLayoutType::DataLayoutNd").finish()
            }
            DataLayoutType::DataLayoutNchw => {
              f.debug_tuple("DataLayoutType::DataLayoutNchw").finish()
            }
            DataLayoutType::DataLayoutNhwc => {
              f.debug_tuple("DataLayoutType::DataLayoutNhwc").finish()
            }
            DataLayoutType::DataLayoutNdhwc => {
              f.debug_tuple("DataLayoutType::DataLayoutNdhwc").finish()
            }
            DataLayoutType::DataLayoutPlanar => {
              f.debug_tuple("DataLayoutType::DataLayoutPlanar").finish()
            }
          }
        }
      }

      impl DataLayoutType{
        #[doc(hidden)]
        pub unsafe fn _lift(val: u8) -> DataLayoutType{
          if !cfg!(debug_assertions) {
            return ::core::mem::transmute(val);
          }

          match val {
            0 => DataLayoutType::DataLayoutUnknown,
            1 => DataLayoutType::DataLayoutNd,
            2 => DataLayoutType::DataLayoutNchw,
            3 => DataLayoutType::DataLayoutNhwc,
            4 => DataLayoutType::DataLayoutNdhwc,
            5 => DataLayoutType::DataLayoutPlanar,

            _ => panic!("invalid enum discriminant"),
          }
        }
      }

      #[repr(u8)]
      #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
      pub enum PaddingModeType {
        PaddingModeNull,
        PaddingModeCropCenter,
        PaddingModeLetterbox,
      }
      impl ::core::fmt::Debug for PaddingModeType {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          match self {
            PaddingModeType::PaddingModeNull => {
              f.debug_tuple("PaddingModeType::PaddingModeNull").finish()
            }
            PaddingModeType::PaddingModeCropCenter => {
              f.debug_tuple("PaddingModeType::PaddingModeCropCenter").finish()
            }
            PaddingModeType::PaddingModeLetterbox => {
              f.debug_tuple("PaddingModeType::PaddingModeLetterbox").finish()
            }
          }
        }
      }

      impl PaddingModeType{
        #[doc(hidden)]
        pub unsafe fn _lift(val: u8) -> PaddingModeType{
          if !cfg!(debug_assertions) {
            return ::core::mem::transmute(val);
          }

          match val {
            0 => PaddingModeType::PaddingModeNull,
            1 => PaddingModeType::PaddingModeCropCenter,
            2 => PaddingModeType::PaddingModeLetterbox,

            _ => panic!("invalid enum discriminant"),
          }
        }
      }


      #[derive(Debug)]
      #[repr(transparent)]
      pub struct Layer{
        handle: _rt::Resource<Layer>,
      }

      impl Layer{
        #[doc(hidden)]
        pub unsafe fn from_handle(handle: u32) -> Self {
          Self {
            handle: _rt::Resource::from_handle(handle),
          }
        }

        #[doc(hidden)]
        pub fn take_handle(&self) -> u32 {
          _rt::Resource::take_handle(&self.handle)
        }

        #[doc(hidden)]
        pub fn handle(&self) -> u32 {
          _rt::Resource::handle(&self.handle)
        }
      }


      unsafe impl _rt::WasmResource for Layer{
        #[inline]
        unsafe fn drop(_handle: u32) {
          #[cfg(not(target_arch = "wasm32"))]
          unreachable!();

          #[cfg(target_arch = "wasm32")]
          {
            #[link(wasm_import_module = "wasm:cv/net")]
            extern "C" {
              #[link_name = "[resource-drop]layer"]
              fn drop(_: u32);
            }

            drop(_handle);
          }
        }
      }


      #[derive(Debug)]
      #[repr(transparent)]
      pub struct Net{
        handle: _rt::Resource<Net>,
      }

      impl Net{
        #[doc(hidden)]
        pub unsafe fn from_handle(handle: u32) -> Self {
          Self {
            handle: _rt::Resource::from_handle(handle),
          }
        }

        #[doc(hidden)]
        pub fn take_handle(&self) -> u32 {
          _rt::Resource::take_handle(&self.handle)
        }

        #[doc(hidden)]
        pub fn handle(&self) -> u32 {
          _rt::Resource::handle(&self.handle)
        }
      }


      unsafe impl _rt::WasmResource for Net{
        #[inline]
        unsafe fn drop(_handle: u32) {
          #[cfg(not(target_arch = "wasm32"))]
          unreachable!();

          #[cfg(target_arch = "wasm32")]
          {
            #[link(wasm_import_module = "wasm:cv/net")]
            extern "C" {
              #[link_name = "[resource-drop]net"]
              fn drop(_: u32);
            }

            drop(_handle);
          }
        }
      }

      impl Layer {
        #[allow(unused_unsafe, clippy::all)]
        pub fn new() -> Self{
          unsafe {

            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "wasm:cv/net")]
            extern "C" {
              #[link_name = "[constructor]layer"]
              fn wit_import() -> i32;
            }

            #[cfg(not(target_arch = "wasm32"))]
            fn wit_import() -> i32{ unreachable!() }
            let ret = wit_import();
            Layer::from_handle(ret as u32)
          }
        }
      }
      impl Layer {
        #[allow(unused_unsafe, clippy::all)]
        /// GetName returns the name of the layer.
        pub fn get_name(&self,) -> _rt::String{
          unsafe {
            #[repr(align(4))]
            struct RetArea([::core::mem::MaybeUninit::<u8>; 8]);
            let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 8]);
            let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "wasm:cv/net")]
            extern "C" {
              #[link_name = "[method]layer.get-name"]
              fn wit_import(_: i32, _: *mut u8, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            fn wit_import(_: i32, _: *mut u8, ){ unreachable!() }
            wit_import((self).handle() as i32, ptr0);
            let l1 = *ptr0.add(0).cast::<*mut u8>();
            let l2 = *ptr0.add(4).cast::<usize>();
            let len3 = l2;
            let bytes3 = _rt::Vec::from_raw_parts(l1.cast(), len3, len3);
            _rt::string_lift(bytes3)
          }
        }
      }
      impl Net {
        #[allow(unused_unsafe, clippy::all)]
        pub fn new() -> Self{
          unsafe {

            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "wasm:cv/net")]
            extern "C" {
              #[link_name = "[constructor]net"]
              fn wit_import() -> i32;
            }

            #[cfg(not(target_arch = "wasm32"))]
            fn wit_import() -> i32{ unreachable!() }
            let ret = wit_import();
            Net::from_handle(ret as u32)
          }
        }
      }
      impl Net {
        #[allow(unused_unsafe, clippy::all)]
        /// close the network
        pub fn close(&self,){
          unsafe {

            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "wasm:cv/net")]
            extern "C" {
              #[link_name = "[method]net.close"]
              fn wit_import(_: i32, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            fn wit_import(_: i32, ){ unreachable!() }
            wit_import((self).handle() as i32);
          }
        }
      }
      impl Net {
        #[allow(unused_unsafe, clippy::all)]
        /// ReadNetFromONNX reads a network model stored in ONNX framework's format.
        ///
        /// For further details, please see:
        /// https://docs.opencv.org/4.x/d6/d0f/group__dnn.html#ga9198ecaac7c32ddf0aa7a1bcbd359567
        pub fn read_net_from_onnx(model: &str,) -> Net{
          unsafe {
            let vec0 = model;
            let ptr0 = vec0.as_ptr().cast::<u8>();
            let len0 = vec0.len();

            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "wasm:cv/net")]
            extern "C" {
              #[link_name = "[static]net.read-net-from-onnx"]
              fn wit_import(_: *mut u8, _: usize, ) -> i32;
            }

            #[cfg(not(target_arch = "wasm32"))]
            fn wit_import(_: *mut u8, _: usize, ) -> i32{ unreachable!() }
            let ret = wit_import(ptr0.cast_mut(), len0);
            Net::from_handle(ret as u32)
          }
        }
      }
      impl Net {
        #[allow(unused_unsafe, clippy::all)]
        /// Empty returns true if there are no layers in the network.
        ///
        /// For further details, please see:
        /// https://docs.opencv.org/master/db/d30/classcv_1_1dnn_1_1Net.html#a6a5778787d5b8770deab5eda6968e66c
        pub fn empty(&self,) -> bool{
          unsafe {

            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "wasm:cv/net")]
            extern "C" {
              #[link_name = "[method]net.empty"]
              fn wit_import(_: i32, ) -> i32;
            }

            #[cfg(not(target_arch = "wasm32"))]
            fn wit_import(_: i32, ) -> i32{ unreachable!() }
            let ret = wit_import((self).handle() as i32);
            _rt::bool_lift(ret as u8)
          }
        }
      }
      impl Net {
        #[allow(unused_unsafe, clippy::all)]
        /// SetInput sets the new input value for the network.
        ///
        /// For further details, please see:
        /// https://docs.opencv.org/trunk/db/d30/classcv_1_1dnn_1_1Net.html#a672a08ae76444d75d05d7bfea3e4a328
        pub fn set_input(&self,input: Mat,name: &str,){
          unsafe {
            let vec0 = name;
            let ptr0 = vec0.as_ptr().cast::<u8>();
            let len0 = vec0.len();

            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "wasm:cv/net")]
            extern "C" {
              #[link_name = "[method]net.set-input"]
              fn wit_import(_: i32, _: i32, _: *mut u8, _: usize, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            fn wit_import(_: i32, _: i32, _: *mut u8, _: usize, ){ unreachable!() }
            wit_import((self).handle() as i32, (&input).take_handle() as i32, ptr0.cast_mut(), len0);
          }
        }
      }
      impl Net {
        #[allow(unused_unsafe, clippy::all)]
        /// Forward runs forward pass to compute output of layer with name outputName.
        ///
        /// For further details, please see:
        /// https://docs.opencv.org/trunk/db/d30/classcv_1_1dnn_1_1Net.html#a98ed94cb6ef7063d3697259566da310b
        pub fn forward(&self,output_name: &str,) -> Mat{
          unsafe {
            let vec0 = output_name;
            let ptr0 = vec0.as_ptr().cast::<u8>();
            let len0 = vec0.len();

            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "wasm:cv/net")]
            extern "C" {
              #[link_name = "[method]net.forward"]
              fn wit_import(_: i32, _: *mut u8, _: usize, ) -> i32;
            }

            #[cfg(not(target_arch = "wasm32"))]
            fn wit_import(_: i32, _: *mut u8, _: usize, ) -> i32{ unreachable!() }
            let ret = wit_import((self).handle() as i32, ptr0.cast_mut(), len0);
            super::super::super::wasm::cv::mat::Mat::from_handle(ret as u32)
          }
        }
      }
      impl Net {
        #[allow(unused_unsafe, clippy::all)]
        /// GetUnconnectedOutLayers returns indexes of layers with unconnected outputs.
        ///
        /// For further details, please see:
        /// https://docs.opencv.org/4.x/db/d30/classcv_1_1dnn_1_1Net.html#ae26f0c29b3733d15d0482098ef9053e3
        pub fn get_unconnected_out_layers(&self,) -> _rt::Vec::<u32>{
          unsafe {
            #[repr(align(4))]
            struct RetArea([::core::mem::MaybeUninit::<u8>; 8]);
            let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 8]);
            let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "wasm:cv/net")]
            extern "C" {
              #[link_name = "[method]net.get-unconnected-out-layers"]
              fn wit_import(_: i32, _: *mut u8, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            fn wit_import(_: i32, _: *mut u8, ){ unreachable!() }
            wit_import((self).handle() as i32, ptr0);
            let l1 = *ptr0.add(0).cast::<*mut u8>();
            let l2 = *ptr0.add(4).cast::<usize>();
            let len3 = l2;
            _rt::Vec::from_raw_parts(l1.cast(), len3, len3)
          }
        }
      }
      impl Net {
        #[allow(unused_unsafe, clippy::all)]
        /// GetLayerNames returns names of layers in the network.
        ///
        /// For further details, please see:
        /// hhttps://docs.opencv.org/4.x/db/d30/classcv_1_1dnn_1_1Net.html#a38e67098ae4ae5906bf8d8ea72199c2e
        pub fn get_layer_names(&self,) -> _rt::Vec::<_rt::String>{
          unsafe {
            #[repr(align(4))]
            struct RetArea([::core::mem::MaybeUninit::<u8>; 8]);
            let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 8]);
            let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "wasm:cv/net")]
            extern "C" {
              #[link_name = "[method]net.get-layer-names"]
              fn wit_import(_: i32, _: *mut u8, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            fn wit_import(_: i32, _: *mut u8, ){ unreachable!() }
            wit_import((self).handle() as i32, ptr0);
            let l1 = *ptr0.add(0).cast::<*mut u8>();
            let l2 = *ptr0.add(4).cast::<usize>();
            let base6 = l1;
            let len6 = l2;
            let mut result6 = _rt::Vec::with_capacity(len6);
            for i in 0..len6 {
              let base = base6.add(i * 8);
              let e6 = {
                let l3 = *base.add(0).cast::<*mut u8>();
                let l4 = *base.add(4).cast::<usize>();
                let len5 = l4;
                let bytes5 = _rt::Vec::from_raw_parts(l3.cast(), len5, len5);

                _rt::string_lift(bytes5)
              };
              result6.push(e6);
            }
            _rt::cabi_dealloc(base6, len6 * 8, 4);
            result6
          }
        }
      }
      impl Net {
        #[allow(unused_unsafe, clippy::all)]
        /// GetLayer returns layer with specified id.
        ///
        /// For further details, please see:
        /// https://docs.opencv.org/4.x/db/d30/classcv_1_1dnn_1_1Net.html#ac944d7f2d3ead5ef9b1b2fa3885f3ff1
        pub fn get_layer(&self,id: u32,) -> Layer{
          unsafe {

            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "wasm:cv/net")]
            extern "C" {
              #[link_name = "[method]net.get-layer"]
              fn wit_import(_: i32, _: i32, ) -> i32;
            }

            #[cfg(not(target_arch = "wasm32"))]
            fn wit_import(_: i32, _: i32, ) -> i32{ unreachable!() }
            let ret = wit_import((self).handle() as i32, _rt::as_i32(&id));
            Layer::from_handle(ret as u32)
          }
        }
      }

    }

  }
}
#[allow(dead_code)]
pub mod exports {
  #[allow(dead_code)]
  pub mod wasm {
    #[allow(dead_code)]
    pub mod cv {
      #[allow(dead_code, clippy::all)]
      pub mod request {
        #[used]
        #[doc(hidden)]
        static __FORCE_SECTION_REF: fn() =
        super::super::super::super::__link_custom_section_describing_imports;
        
        use super::super::super::super::_rt;
        pub type Mat = super::super::super::super::wasm::cv::mat::Mat;
        #[doc(hidden)]
        #[allow(non_snake_case)]
        pub unsafe fn _export_process_cabi<T: Guest>(arg0: i32,) -> i32 {#[cfg(target_arch="wasm32")]
        _rt::run_ctors_once();let result0 = T::process(super::super::super::super::wasm::cv::mat::Mat::from_handle(arg0 as u32));
        (result0).take_handle() as i32
      }
      pub trait Guest {
        fn process(image: Mat,) -> Mat;
      }
      #[doc(hidden)]

      macro_rules! __export_wasm_cv_request_cabi{
        ($ty:ident with_types_in $($path_to_types:tt)*) => (const _: () = {

          #[export_name = "wasm:cv/request#process"]
          unsafe extern "C" fn export_process(arg0: i32,) -> i32 {
            $($path_to_types)*::_export_process_cabi::<$ty>(arg0)
          }
        };);
      }
      #[doc(hidden)]
      pub(crate) use __export_wasm_cv_request_cabi;

    }

  }
}
}
mod _rt {


  use core::fmt;
  use core::marker;
  use core::sync::atomic::{AtomicU32, Ordering::Relaxed};

  /// A type which represents a component model resource, either imported or
  /// exported into this component.
  ///
  /// This is a low-level wrapper which handles the lifetime of the resource
  /// (namely this has a destructor). The `T` provided defines the component model
  /// intrinsics that this wrapper uses.
  ///
  /// One of the chief purposes of this type is to provide `Deref` implementations
  /// to access the underlying data when it is owned.
  ///
  /// This type is primarily used in generated code for exported and imported
  /// resources.
  #[repr(transparent)]
  pub struct Resource<T: WasmResource> {
    // NB: This would ideally be `u32` but it is not. The fact that this has
    // interior mutability is not exposed in the API of this type except for the
    // `take_handle` method which is supposed to in theory be private.
    //
    // This represents, almost all the time, a valid handle value. When it's
    // invalid it's stored as `u32::MAX`.
    handle: AtomicU32,
    _marker: marker::PhantomData<T>,
  }

  /// A trait which all wasm resources implement, namely providing the ability to
  /// drop a resource.
  ///
  /// This generally is implemented by generated code, not user-facing code.
  #[allow(clippy::missing_safety_doc)]
  pub unsafe trait WasmResource {
    /// Invokes the `[resource-drop]...` intrinsic.
    unsafe fn drop(handle: u32);
  }

  impl<T: WasmResource> Resource<T> {
    #[doc(hidden)]
    pub unsafe fn from_handle(handle: u32) -> Self {
      debug_assert!(handle != u32::MAX);
      Self {
        handle: AtomicU32::new(handle),
        _marker: marker::PhantomData,
      }
    }

    /// Takes ownership of the handle owned by `resource`.
    ///
    /// Note that this ideally would be `into_handle` taking `Resource<T>` by
    /// ownership. The code generator does not enable that in all situations,
    /// unfortunately, so this is provided instead.
    ///
    /// Also note that `take_handle` is in theory only ever called on values
    /// owned by a generated function. For example a generated function might
    /// take `Resource<T>` as an argument but then call `take_handle` on a
    /// reference to that argument. In that sense the dynamic nature of
    /// `take_handle` should only be exposed internally to generated code, not
    /// to user code.
    #[doc(hidden)]
    pub fn take_handle(resource: &Resource<T>) -> u32 {
      resource.handle.swap(u32::MAX, Relaxed)
    }

    #[doc(hidden)]
    pub fn handle(resource: &Resource<T>) -> u32 {
      resource.handle.load(Relaxed)
    }
  }

  impl<T: WasmResource> fmt::Debug for Resource<T> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
      f.debug_struct("Resource")
      .field("handle", &self.handle)
      .finish()
    }
  }

  impl<T: WasmResource> Drop for Resource<T> {
    fn drop(&mut self) {
      unsafe {
        match self.handle.load(Relaxed) {
          // If this handle was "taken" then don't do anything in the
          // destructor.
          u32::MAX => {}

          // ... but otherwise do actually destroy it with the imported
          // component model intrinsic as defined through `T`.
          other => T::drop(other),
        }
      }
    }
  }
  
  pub fn as_i32<T: AsI32>(t: T) -> i32 {
    t.as_i32()
  }

  pub trait AsI32 {
    fn as_i32(self) -> i32;
  }

  impl<'a, T: Copy + AsI32> AsI32 for &'a T {
    fn as_i32(self) -> i32 {
      (*self).as_i32()
    }
  }
  
  impl AsI32 for i32 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for u32 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for i16 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for u16 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for i8 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for u8 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for char {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for usize {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  pub use alloc_crate::vec::Vec;
  pub unsafe fn bool_lift(val: u8) -> bool {
    if cfg!(debug_assertions) {
      match val {
        0 => false,
        1 => true,
        _ => panic!("invalid bool discriminant"),
      }
    } else {
      val != 0
    }
  }
  pub use alloc_crate::string::String;
  pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
    if cfg!(debug_assertions) {
      String::from_utf8(bytes).unwrap()
    } else {
      String::from_utf8_unchecked(bytes)
    }
  }
  pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
    if size == 0 {
      return;
    }
    let layout = alloc::Layout::from_size_align_unchecked(size, align);
    alloc::dealloc(ptr, layout);
  }
  
  pub fn as_f32<T: AsF32>(t: T) -> f32 {
    t.as_f32()
  }

  pub trait AsF32 {
    fn as_f32(self) -> f32;
  }

  impl<'a, T: Copy + AsF32> AsF32 for &'a T {
    fn as_f32(self) -> f32 {
      (*self).as_f32()
    }
  }
  
  impl AsF32 for f32 {
    #[inline]
    fn as_f32(self) -> f32 {
      self as f32
    }
  }
  
  #[cfg(target_arch = "wasm32")]
  pub fn run_ctors_once() {
    wit_bindgen::rt::run_ctors_once();
  }
  extern crate alloc as alloc_crate;
  pub use alloc_crate::alloc;
}

/// Generates `#[no_mangle]` functions to export the specified type as the
/// root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]

macro_rules! __export_cv_impl {
  ($ty:ident) => (self::export!($ty with_types_in self););
  ($ty:ident with_types_in $($path_to_types_root:tt)*) => (
  $($path_to_types_root)*::exports::wasm::cv::request::__export_wasm_cv_request_cabi!($ty with_types_in $($path_to_types_root)*::exports::wasm::cv::request);
  )
}
#[doc(inline)]
pub(crate) use __export_cv_impl as export;

#[cfg(target_arch = "wasm32")]
#[link_section = "component-type:wit-bindgen:0.31.0:wasm:cv:cv:encoded world"]
#[doc(hidden)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 2491] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xc2\x12\x01A\x02\x01\
A\x1d\x01B\x08\x01r\x02\x01xz\x01yz\x04\0\x04size\x03\0\0\x01m\x08\x0fborder-con\
stant\x10border-replicate\x0eborder-reflect\x0bborder-wrap\x11border-reflect101\x12\
border-transparent\x0eborder-default\x0fborder-isolated\x04\0\x0bborder-type\x03\
\0\x02\x01m\x02\x17adaptive-threshold-mean\x1badaptive-threshold-gaussian\x04\0\x17\
adaptive-threshold-type\x03\0\x04\x01m\x08\x10threshold-binary\x14threshold-bina\
ry-inv\x0fthreshold-trunc\x11threshold-to-zero\x15threshold-to-zero-inv\x0ethres\
hold-mask\x0ethreshold-otsu\x13tthreshold-triangle\x04\0\x0ethreshold-type\x03\0\
\x06\x03\x01\x0dwasm:cv/types\x05\0\x01B\x15\x01m\x07\x04cv8u\x04cv8s\x05cv16u\x05\
cv16s\x05cv32s\x05cv32f\x05cv64f\x04\0\x07mattype\x03\0\0\x04\0\x03mat\x03\x01\x01\
i\x02\x01@\x03\x04colsy\x04rowsy\x04type\x01\0\x03\x04\0\x10[constructor]mat\x01\
\x04\x01h\x02\x01@\x01\x04self\x05\x01\0\x04\0\x11[method]mat.close\x01\x06\x01@\
\x01\x04self\x05\0y\x04\0\x10[method]mat.cols\x01\x07\x04\0\x10[method]mat.rows\x01\
\x07\x01@\x01\x04self\x05\0\x01\x04\0\x10[method]mat.type\x01\x08\x01py\x01@\x01\
\x04self\x05\0\x09\x04\0\x10[method]mat.size\x01\x0a\x01@\x01\x04self\x05\0\x7f\x04\
\0\x11[method]mat.empty\x01\x0b\x01@\x03\x04self\x05\x08channelsy\x04rowsy\0\x03\
\x04\0\x13[method]mat.reshape\x01\x0c\x03\x01\x0bwasm:cv/mat\x05\x01\x02\x03\0\0\
\x0bborder-type\x03\0\x0bborder-type\x03\0\x02\x02\x03\0\0\x04size\x03\0\x04size\
\x03\0\x04\x02\x03\0\0\x17adaptive-threshold-type\x03\0\x17adaptive-threshold-ty\
pe\x03\0\x06\x02\x03\0\0\x0ethreshold-type\x03\0\x0ethreshold-type\x03\0\x08\x02\
\x03\0\x01\x03mat\x03\0\x03mat\x03\0\x0a\x01i\x0b\x01@\x06\x03src\x0c\x09max-val\
uev\x0dadaptive-type\x07\x0ethreshold-type\x09\x0ablock-sizey\x01cv\0\x0c\x03\0\x12\
adaptive-threshold\x01\x0d\x01@\x02\x03src\x0c\x06k-size\x05\0\x0c\x03\0\x04blur\
\x01\x0e\x01@\x03\x03src\x0c\x05depthy\x06k-size\x05\0\x0c\x03\0\x0abox-filter\x01\
\x0f\x01@\x05\x03src\x0c\x04size\x05\x07sigma-xv\x07sigma-yv\x06border\x03\0\x0c\
\x03\0\x0dgaussian-blur\x01\x10\x01@\x04\x03src\x0c\x06threshv\x09max-valuev\x0e\
threshold-type\x09\0\x0c\x03\0\x09threshold\x01\x11\x01B)\x02\x03\x02\x01\x0a\x04\
\0\x03mat\x03\0\0\x01m\x06\x13net-backend-default\x12net-backend-halide\x14net-b\
ackend-openvino\x12net-backend-opencv\x11net-backend-vkcom\x10net-backend-cuda\x04\
\0\x10net-backend-type\x03\0\x02\x01m\x08\x0enet-target-cpu\x0fnet-target-fp32\x0f\
net-target-fp16\x0enet-target-vpu\x11net-target-vulkan\x0fnet-target-fpga\x0fnet\
-target-cuda\x14net-target-cuda-fp16\x04\0\x0fnet-target-type\x03\0\x04\x01m\x06\
\x13data-layout-unknown\x0edata-layout-nd\x10data-layout-nchw\x10data-layout-nhw\
c\x11data-layout-ndhwc\x12data-layout-planar\x04\0\x10data-layout-type\x03\0\x06\
\x01m\x03\x11padding-mode-null\x18padding-mode-crop-center\x16padding-mode-lette\
rbox\x04\0\x11padding-mode-type\x03\0\x08\x04\0\x05layer\x03\x01\x04\0\x03net\x03\
\x01\x01i\x0a\x01@\0\0\x0c\x04\0\x12[constructor]layer\x01\x0d\x01h\x0a\x01@\x01\
\x04self\x0e\0s\x04\0\x16[method]layer.get-name\x01\x0f\x01i\x0b\x01@\0\0\x10\x04\
\0\x10[constructor]net\x01\x11\x01h\x0b\x01@\x01\x04self\x12\x01\0\x04\0\x11[met\
hod]net.close\x01\x13\x01@\x01\x05models\0\x10\x04\0\x1e[static]net.read-net-fro\
m-onnx\x01\x14\x01@\x01\x04self\x12\0\x7f\x04\0\x11[method]net.empty\x01\x15\x01\
i\x01\x01@\x03\x04self\x12\x05input\x16\x04names\x01\0\x04\0\x15[method]net.set-\
input\x01\x17\x01@\x02\x04self\x12\x0boutput-names\0\x16\x04\0\x13[method]net.fo\
rward\x01\x18\x01py\x01@\x01\x04self\x12\0\x19\x04\0&[method]net.get-unconnected\
-out-layers\x01\x1a\x01ps\x01@\x01\x04self\x12\0\x1b\x04\0\x1b[method]net.get-la\
yer-names\x01\x1c\x01@\x02\x04self\x12\x02idy\0\x0c\x04\0\x15[method]net.get-lay\
er\x01\x1d\x03\x01\x0bwasm:cv/net\x05\x12\x01B\x05\x02\x03\x02\x01\x0a\x04\0\x03\
mat\x03\0\0\x01i\x01\x01@\x01\x05image\x02\0\x02\x04\0\x07process\x01\x03\x04\x01\
\x0fwasm:cv/request\x05\x13\x04\x01\x0awasm:cv/cv\x04\0\x0b\x08\x01\0\x02cv\x03\0\
\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-component\x070.216.0\x10wit-bi\
ndgen-rust\x060.31.0";

#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
  wit_bindgen::rt::maybe_link_cabi_realloc();
}

