
interface cv {
    use types.{border-type, size, adaptive-threshold-type, threshold-type, scalar, rect, rgba, hershey-font-type, interpolation-type, color-coversion-type};
    use mat.{mat, mattype};

    // drawing functions

    /// ArrowedLine draws a arrow segment pointing from the first point to the second one.
    ///
    /// For further details, please see:
    /// https://docs.opencv.org/master/d6/d6e/group__imgproc__draw.html#ga0a165a3ca093fd488ac709fdf10c05b2
    arrowed-line: func(img: mat, point1: size, point2: size, c: rgba, thickness: u8);

    /// Rectangle draws a simple, thick, or filled up-right rectangle.
    ///
    /// For further details, please see:
    /// https://docs.opencv.org/4.x/d6/d6e/group__imgproc__draw.html#ga07d2f74cadcf8e305e810ce8f3d1e1b7
    rectangle: func(img: mat, r: rect, c: rgba, thickness: u8);

    /// Circle draws a circle.
    ///
    /// For further details, please see:
    /// https://docs.opencv.org/master/d6/d6e/group__imgproc__draw.html#gaf10604b069374903dbd0f0488cb43670
    circle: func(img: mat, center: size, radius: u32, c: rgba, thickness: u8);

    /// Line draws a line segment connecting two points.
    ///
    /// For further details, please see:
    /// https://docs.opencv.org/master/d6/d6e/group__imgproc__draw.html#ga7078a9fae8c7e7d13d24dac2520ae4a2
    line: func(img: mat, point1: size, point2: size, c: rgba, thickness: u8);

    /// PutText draws a text string.
    /// It renders the specified text string into the img Mat at the location
    /// passed in the "org" param, using the desired font face, font scale,
    /// color, and line thinkness.
    ///
    /// For further details, please see:
    /// http://docs.opencv.org/master/d6/d6e/group__imgproc__draw.html#ga5126f47f883d730f633d74f07456c576
    put-text: func(img: mat, text: string, org: size, font-face: hershey-font-type, font-scale: f64, c: rgba, thickness: s32);

    // imgproc functions

    /// AdaptiveThreshold applies a fixed-level threshold to each array element.
    ///
    /// For further details, please see:
    /// https://docs.opencv.org/master/d7/d1b/group__imgproc__misc.html#ga72b913f352e4a1b1b397736707afcde3
    adaptive-threshold: func(src: mat, max-value: f32, adaptive-type: adaptive-threshold-type, threshold-type: threshold-type, block-size: u32, c: f32) -> mat;

    /// Blur blurs an image Mat using a normalized box filter.
    ///
    /// For further details, please see:
    /// https://docs.opencv.org/master/d4/d86/group__imgproc__filter.html#ga8c45db9afe636703801b0b2e440fce37
    blur: func(src: mat, k-size: size) -> mat;

    /// BoxFilter blurs an image using the box filter.
    ///
    /// For further details, please see:
    /// https://docs.opencv.org/master/d4/d86/group__imgproc__filter.html#gad533230ebf2d42509547d514f7d3fbc3
    box-filter: func(src: mat, depth: u32, k-size: size) -> mat;

    /// GaussianBlur blurs an image using a Gaussian filter.
    ///
    /// For further details, please see:
    /// https://docs.opencv.org/4.x/d4/d86/group__imgproc__filter.html#gae8bdcd9154ed5ca3cbc1766d960f45c1
    gaussian-blur: func(src: mat, size: size, sigma-x: f32, sigma-y: f32, border: border-type) -> mat;

    /// MedianBlur blurs an image using the median filter.
    ///
    /// For further details, please see:
    /// https://docs.opencv.org/master/d4/d86/group__imgproc__filter.html#ga564869aa33e58769b4469101aac458f9
    median-blur: func(src: mat, k-size: size) -> mat;

    /// Threshold applies a fixed-level threshold to each array element.
    ///
    /// For further details, please see:
    /// https://docs.opencv.org/3.3.0/d7/d1b/group__imgproc__misc.html#gae8a4a146d1ca78c626a53577199e9c57
    threshold: func(src: mat, thresh: f32, max-value: f32, threshold-type: threshold-type) -> mat;

    /// CvtColor converts an image from one color space to another.
    ///
    /// For further details, please see:
    /// http://docs.opencv.org/master/d7/d1b/group__imgproc__misc.html#ga4e0972be5de079fed4e3a10e24ef5ef0
    cvt-color: func(src: mat, code: color-coversion-type) -> mat;

    /// Transpose for n-dimensional matrices.
    ///
    /// For further details, please see:
    /// https://docs.opencv.org/4.x/d2/de8/group__core__array.html#gab1b1274b4a563be34cdfa55b8919a4ec
    transpose-nd: func(src: mat, order: list<s32>) -> mat;

    /// Resize resizes an image.
    /// It resizes the image src down to or up to the specified size, storing the
    /// result in dst. Note that src and dst may be the same image. If you wish to
    /// scale by factor, an empty sz may be passed and non-zero fx and fy. Likewise,
    /// if you wish to scale to an explicit size, a non-empty sz may be passed with
    /// zero for both fx and fy.
    ///
    /// For further details, please see:
    /// https://docs.opencv.org/master/da/d54/group__imgproc__transform.html#ga47a974309e9102f5f08231edc7e7529d
    resize: func(src: mat, size: size, fx: f32, fy: f32, interp: interpolation-type) -> mat;
}
