package wasm:cv;

interface types {
    record size {
        x: s32,
        y: s32,
    }

    enum border-type {
        border-constant,
        border-replicate,
        border-reflect,
        border-wrap,
        border-reflect101,
        border-transparent,
        border-default,
        border-isolated,
    }

    enum adaptive-threshold-type {
        adaptive-threshold-mean,
        adaptive-threshold-gaussian,
    }
    
    enum threshold-type {
        threshold-binary,
        threshold-binary-inv,
        threshold-trunc,
        threshold-to-zero,
        threshold-to-zero-inv,
        threshold-mask,
        threshold-otsu,
        tthreshold-triangle,
    }
}
