package wasm:cv;
/// wasmCV is a WebAssembly guest module interface for computer vision based on OpenCV.
///
world cv {
    import types;
    import mat;

    include core;
    include dnn;

    export request;
}
