package wasm:cv;
/// wasmCV is a WebAssembly guest module interface for computer vision based on OpenCV.
///
world imports {
    import types;
    import mat;

    import cv;
    import dnn;
    import objdetect;

    export request;
}
