// Generated by `wit-bindgen` 0.31.0. DO NOT EDIT!
#include "cv.h"
#include <stdlib.h>

// Imported Functions from `wasm:cv/mat`

__attribute__((__import_module__("wasm:cv/mat"), __import_name__("[constructor]mat")))
extern int32_t __wasm_import_wasm_cv_mat_constructor_mat(int32_t, int32_t, int32_t);

__attribute__((__import_module__("wasm:cv/mat"), __import_name__("[method]mat.close")))
extern void __wasm_import_wasm_cv_mat_method_mat_close(int32_t);

__attribute__((__import_module__("wasm:cv/mat"), __import_name__("[method]mat.cols")))
extern int32_t __wasm_import_wasm_cv_mat_method_mat_cols(int32_t);

__attribute__((__import_module__("wasm:cv/mat"), __import_name__("[method]mat.rows")))
extern int32_t __wasm_import_wasm_cv_mat_method_mat_rows(int32_t);

__attribute__((__import_module__("wasm:cv/mat"), __import_name__("[method]mat.type")))
extern int32_t __wasm_import_wasm_cv_mat_method_mat_type(int32_t);

__attribute__((__import_module__("wasm:cv/mat"), __import_name__("[method]mat.size")))
extern int32_t __wasm_import_wasm_cv_mat_method_mat_size(int32_t);

// Canonical ABI intrinsics

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

// Helper Functions

__attribute__((__import_module__("wasm:cv/mat"), __import_name__("[resource-drop]mat")))
extern void __wasm_import_wasm_cv_mat_mat_drop(int32_t handle);

void wasm_cv_mat_mat_drop_own(wasm_cv_mat_own_mat_t handle) {
  __wasm_import_wasm_cv_mat_mat_drop(handle.__handle);
}

wasm_cv_mat_borrow_mat_t wasm_cv_mat_borrow_mat(wasm_cv_mat_own_mat_t arg) {
  return (wasm_cv_mat_borrow_mat_t) { arg.__handle };
}

// Component Adapters

wasm_cv_mat_own_mat_t wasm_cv_mat_constructor_mat(uint32_t cols, uint32_t rows, wasm_cv_mat_mattype_t type) {
  int32_t ret = __wasm_import_wasm_cv_mat_constructor_mat((int32_t) (cols), (int32_t) (rows), (int32_t) type);
  return (wasm_cv_mat_own_mat_t) { ret };
}

void wasm_cv_mat_method_mat_close(wasm_cv_mat_borrow_mat_t self) {
  __wasm_import_wasm_cv_mat_method_mat_close((self).__handle);
}

uint32_t wasm_cv_mat_method_mat_cols(wasm_cv_mat_borrow_mat_t self) {
  int32_t ret = __wasm_import_wasm_cv_mat_method_mat_cols((self).__handle);
  return (uint32_t) (ret);
}

uint32_t wasm_cv_mat_method_mat_rows(wasm_cv_mat_borrow_mat_t self) {
  int32_t ret = __wasm_import_wasm_cv_mat_method_mat_rows((self).__handle);
  return (uint32_t) (ret);
}

wasm_cv_mat_mattype_t wasm_cv_mat_method_mat_type(wasm_cv_mat_borrow_mat_t self) {
  int32_t ret = __wasm_import_wasm_cv_mat_method_mat_type((self).__handle);
  return ret;
}

uint32_t wasm_cv_mat_method_mat_size(wasm_cv_mat_borrow_mat_t self) {
  int32_t ret = __wasm_import_wasm_cv_mat_method_mat_size((self).__handle);
  return (uint32_t) (ret);
}

// Ensure that the *_component_type.o object is linked in

extern void __component_type_object_force_link_cv(void);
void __component_type_object_force_link_cv_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_cv();
}
