// Generated by `wit-bindgen` 0.31.0. DO NOT EDIT!
#ifndef __BINDINGS_CV_H
#define __BINDINGS_CV_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct wasm_cv_types_size_t {
  int32_t   x;
  int32_t   y;
} wasm_cv_types_size_t;

typedef uint8_t wasm_cv_types_border_type_t;

#define WASM_CV_TYPES_BORDER_TYPE_BORDER_CONSTANT 0
#define WASM_CV_TYPES_BORDER_TYPE_BORDER_REPLICATE 1
#define WASM_CV_TYPES_BORDER_TYPE_BORDER_REFLECT 2
#define WASM_CV_TYPES_BORDER_TYPE_BORDER_WRAP 3
#define WASM_CV_TYPES_BORDER_TYPE_BORDER_REFLECT101 4
#define WASM_CV_TYPES_BORDER_TYPE_BORDER_TRANSPARENT 5
#define WASM_CV_TYPES_BORDER_TYPE_BORDER_DEFAULT 6
#define WASM_CV_TYPES_BORDER_TYPE_BORDER_ISOLATED 7

typedef uint8_t wasm_cv_mat_mattype_t;

#define WASM_CV_MAT_MATTYPE_CV8U 0
#define WASM_CV_MAT_MATTYPE_CV8S 1
#define WASM_CV_MAT_MATTYPE_CV16U 2
#define WASM_CV_MAT_MATTYPE_CV16S 3
#define WASM_CV_MAT_MATTYPE_CV32S 4
#define WASM_CV_MAT_MATTYPE_CV32F 5
#define WASM_CV_MAT_MATTYPE_CV64F 6

typedef struct wasm_cv_mat_own_mat_t {
  int32_t __handle;
} wasm_cv_mat_own_mat_t;

typedef struct wasm_cv_mat_borrow_mat_t {
  int32_t __handle;
} wasm_cv_mat_borrow_mat_t;

typedef wasm_cv_types_border_type_t cv_border_type_t;

typedef wasm_cv_types_size_t cv_size_t;

typedef wasm_cv_mat_own_mat_t cv_own_mat_t;

typedef wasm_cv_mat_own_mat_t exports_wasm_cv_request_own_mat_t;

// Imported Functions from `wasm:cv/mat`
extern wasm_cv_mat_own_mat_t wasm_cv_mat_constructor_mat(uint32_t cols, uint32_t rows, wasm_cv_mat_mattype_t type);
extern void wasm_cv_mat_method_mat_close(wasm_cv_mat_borrow_mat_t self);
extern uint32_t wasm_cv_mat_method_mat_cols(wasm_cv_mat_borrow_mat_t self);
extern uint32_t wasm_cv_mat_method_mat_rows(wasm_cv_mat_borrow_mat_t self);
extern wasm_cv_mat_mattype_t wasm_cv_mat_method_mat_type(wasm_cv_mat_borrow_mat_t self);
extern uint32_t wasm_cv_mat_method_mat_size(wasm_cv_mat_borrow_mat_t self);

// Imported Functions from `cv`
// GaussianBlur blurs an image using a Gaussian filter.
// See https://docs.opencv.org/4.x/d4/d86/group__imgproc__filter.html#gae8bdcd9154ed5ca3cbc1766d960f45c1
extern cv_own_mat_t cv_gaussian_blur(cv_own_mat_t input, cv_size_t *size, float sigma_x, float sigma_y, cv_border_type_t border);

// Exported Functions from `wasm:cv/request`
exports_wasm_cv_request_own_mat_t exports_wasm_cv_request_process(exports_wasm_cv_request_own_mat_t image);

// Helper Functions

extern void wasm_cv_mat_mat_drop_own(wasm_cv_mat_own_mat_t handle);

extern wasm_cv_mat_borrow_mat_t wasm_cv_mat_borrow_mat(wasm_cv_mat_own_mat_t handle);


#ifdef __cplusplus
}
#endif
#endif
