// Generated by `wit-bindgen` 0.31.0. DO NOT EDIT!
#ifndef __BINDINGS_CV_H
#define __BINDINGS_CV_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef uint8_t wasm_cv_mat_mattype_t;

#define WASM_CV_MAT_MATTYPE_CV8U 0
#define WASM_CV_MAT_MATTYPE_CV8S 1
#define WASM_CV_MAT_MATTYPE_CV16U 2
#define WASM_CV_MAT_MATTYPE_CV16S 3
#define WASM_CV_MAT_MATTYPE_CV32S 4
#define WASM_CV_MAT_MATTYPE_CV32F 5
#define WASM_CV_MAT_MATTYPE_CV64F 6

typedef struct wasm_cv_mat_own_mat_t {
  int32_t __handle;
} wasm_cv_mat_own_mat_t;

typedef struct wasm_cv_mat_borrow_mat_t {
  int32_t __handle;
} wasm_cv_mat_borrow_mat_t;

// Imported Functions from `wasm:cv/mat`
extern wasm_cv_mat_own_mat_t wasm_cv_mat_constructor_mat(uint32_t cols, uint32_t rows, wasm_cv_mat_mattype_t type);
extern void wasm_cv_mat_method_mat_close(wasm_cv_mat_borrow_mat_t self);
extern uint32_t wasm_cv_mat_method_mat_cols(wasm_cv_mat_borrow_mat_t self);
extern uint32_t wasm_cv_mat_method_mat_rows(wasm_cv_mat_borrow_mat_t self);
extern wasm_cv_mat_mattype_t wasm_cv_mat_method_mat_type(wasm_cv_mat_borrow_mat_t self);
extern uint32_t wasm_cv_mat_method_mat_size(wasm_cv_mat_borrow_mat_t self);

// Helper Functions

extern void wasm_cv_mat_mat_drop_own(wasm_cv_mat_own_mat_t handle);

extern wasm_cv_mat_borrow_mat_t wasm_cv_mat_borrow_mat(wasm_cv_mat_own_mat_t handle);


#ifdef __cplusplus
}
#endif
#endif
